trigger:

- master

pool:

  vmImage: 'ubuntu-latest'

steps:

- task: AzurePowerShell@3

  inputs:

    azureSubscription: 'Visual Studio Professional Subscription (bfe7f0ef-64a4-429c-8146-30faaeba9d4a)'

    ScriptType: 'FilePath'

    ScriptPath: 'Deploy-AzureResourceGroup.ps1'

    ScriptArguments: -Location 'eastus' -ResourceGroupName 'TestingRG' -TemplateFile /deployment/webapp.json

    azurePowerShellVersion: 'LatestVersion'