trigger:

- master

pool:

  vmImage: 'windows-2022'

steps:

- task: AzurePowerShell@3

  inputs:

    azureSubscription: 'Visual Studio Professional Subscription (45f1f18d-50d9-474b-b9b4-87ebc0642c9f)'

    ScriptType: 'FilePath'

    ScriptPath: 'Deploy-AzureResourceGroup.ps1'

    ScriptArguments: -Location 'eastus' -ResourceGroupName 'myResourceGroup' -TemplateFile /deployment/webapp.json -ArtifactStagingDirectory deployment

    azurePowerShellVersion: 'LatestVersion'